---
name: CodeBlocks
author:  Ad5001
version: 1.0
api: [2.0.0]
main: Ad5001\CodeBlocks\Main
commands:
   changecodeblock:
     description: Change the code of a CodeBlock
     usage: "/changecodeblock [password] <code> then tap/click on a block to set the code."
     aliases: ["ccb"]
permissions:
   codeblocks.modify:
     default: op
...